config/routes.rb
Rails.application.routes.draw do

  #API
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do

      resources :itineraries do
        collection do
          post 'plan'
          post 'email'
        end
      end

      resources :places do
        collection do
          get 'search'
          get 'boundary'
          get 'synonyms'
          get 'blacklist'
          post 'within_area'
        end
      end

      resources :defaults do 
        collection do 
          get 'pass'
          post 'pass' 
        end
      end

      resources :defaults, path: '/:type/defaults', constraints: { type: /internal|external/ }

    end
  end

  #Not API

  root 'settings#index'

  resources :settings, :only => [:index] do
    collection do
      patch 'set_callnride_boundary'
      patch 'set_landmarks_file'
      patch 'set_synonyms_file'
      patch 'set_open_trip_planner'
      patch 'set_blacklisted_places_file'
      patch 'set_global_boundary'
      patch 'set_host'
      patch 'set_support_emails'
    end
  end

end

app/models/setting.rb
class Setting < ActiveRecord::Base

  serialize :value

  validates :key, presence: true
  validates :key, uniqueness: true

  # Returns the value of a setting when you say Setting.<key>
  def self.method_missing(key, *args, &blk)

    setting = Setting.find_by(key: key)
    if setting.nil?
      return nil
    else
      return setting.value
    end

  end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  def index
    @boundary = Setting.where(key: 'callnride_boundary').first_or_initialize
    @landmarks_file = Setting.where(key: 'landmarks_file').first_or_initialize
    @synonyms_file = Setting.where(key: 'synonyms_file').first_or_initialize
    @blacklisted_places_file = Setting.where(key: 'blacklisted_places_file').first_or_initialize
    @open_trip_planner = Setting.where(key: 'open_trip_planner').first_or_initialize
    @global_boundary = Setting.where(key: 'global_boundary').first_or_initialize
    @host = Setting.where(key: 'host').first_or_initialize
    @support_emails = Setting.where(key: 'support_emails').first_or_initialize
  end

  def set_callnride_boundary

    info_msgs = []
    error_msgs = []

    boundary_file = params[:setting][:file] if params[:setting]
    if !boundary_file.nil?
      gs = GeographyService.new
      info_msgs << gs.store_callnride_boundary(boundary_file.tempfile.path)
    else
      error_msgs << "Upload a zip file containing a shape file."
    end


    if error_msgs.size > 0
      flash[:error] = error_msgs.join(' ')
    elsif info_msgs.size > 0
      flash[:success] = info_msgs.join(' ')
    end


    respond_to do |format|
      format.js
      format.html {redirect_to settings_path}
    end
  end

  def set_landmarks_file

    info_msgs = []
    error_msgs = []

    landmarks_file = params[:setting][:value] if params[:setting]

    if !landmarks_file.blank?
      lm = Setting.where(key: 'landmarks_file').first_or_initialize
      lm.value = landmarks_file
      lm.save
    else
      error_msgs << "Landmarks URL cannot be blank."
    end


    if error_msgs.size > 0
      flash[:error] = error_msgs.join(' ')
    elsif info_msgs.size > 0
      flash[:success] = info_msgs.join(' ')
    end


    respond_to do |format|
      format.js
      format.html {redirect_to settings_path}
    end
  end

  def set_synonyms_file

    info_msgs = []
    error_msgs = []

    new_value = params[:setting][:value] if params[:setting]

    if !new_value.blank?
      setting = Setting.where(key: 'synonyms_file').first_or_initialize
      setting.value = new_value
      setting.save
    else
      error_msgs << "Synonyms URL cannot be blank."
    end


    if error_msgs.size > 0
      flash[:error] = error_msgs.join(' ')
    elsif info_msgs.size > 0
      flash[:success] = info_msgs.join(' ')
    end


    respond_to do |format|
      format.js
      format.html {redirect_to settings_path}
    end
  end

  def set_blacklisted_places_file

    info_msgs = []
    error_msgs = []

    new_value = params[:setting][:value] if params[:setting]

    if !new_value.blank?
      setting = Setting.where(key: 'blacklisted_places_file').first_or_initialize
      setting.value = new_value
      setting.save
    else
      error_msgs << "Blacklisted Places URL cannot be blank."
    end


    if error_msgs.size > 0
      flash[:error] = error_msgs.join(' ')
    elsif info_msgs.size > 0
      flash[:success] = info_msgs.join(' ')
    end


    respond_to do |format|
      format.js
      format.html {redirect_to settings_path}
    end
  end

  def set_support_emails
    info_msgs = []
    error_msgs = []

    emails = params[:setting][:value] if params[:setting]

    if !emails.blank?
      setting = Setting.where(key: 'support_emails').first_or_initialize
      setting.value = emails
      setting.save
    else
      error_msgs << "Emails cannot be blank."
    end


    if error_msgs.size > 0
      flash[:error] = error_msgs.join(' ')
    elsif info_msgs.size > 0
      flash[:success] = info_msgs.join(' ')
    end


    respond_to do |format|
      format.js
      format.html {redirect_to settings_path}
    end
  end

  def set_global_boundary

    info_msgs = []
    error_msgs = []

    new_value = params[:setting][:value] if params[:setting]

    if !new_value.blank?
      setting = Setting.where(key: 'global_boundary').first_or_initialize
      setting.value = new_value
      setting.save
    else
      setting = Setting.global_boundary
      if setting
        setting.delete
      end
    end


    if error_msgs.size > 0
      flash[:error] = error_msgs.join(' ')
    elsif info_msgs.size > 0
      flash[:success] = info_msgs.join(' ')
    end


    respond_to do |format|
      format.js
      format.html {redirect_to settings_path}
    end
  end

  def set_open_trip_planner

    info_msgs = []
    error_msgs = []

    otp = params[:setting][:value] if params[:setting]

    if !otp.blank?
      setting = Setting.where(key: 'open_trip_planner').first_or_initialize
      setting.value = otp
      setting.save
    else
      error_msgs << "OpenTripPlanner URL cannot be blank."
    end


    if error_msgs.size > 0
      flash[:error] = error_msgs.join(' ')
    elsif info_msgs.size > 0
      flash[:success] = info_msgs.join(' ')
    end


    respond_to do |format|
      format.js
      format.html {redirect_to settings_path}
    end
  end

  def set_host

    info_msgs = []
    error_msgs = []

    value = params[:setting][:value] if params[:setting]

    if !value.blank?
      setting = Setting.where(key: 'host').first_or_initialize
      setting.value = value
      setting.save
    else
      setting = Setting.where(key: 'host').first_or_initialize
      setting.delete
    end


    if error_msgs.size > 0
      flash[:error] = error_msgs.join(' ')
    elsif info_msgs.size > 0
      flash[:success] = info_msgs.join(' ')
    end


    respond_to do |format|
      format.js
      format.html {redirect_to settings_path}
    end
  end

end

app/views/settings/index.html.haml
%h1.text-center
  Settings
%div.row.text-center
  =OtpBuddy::Application.config.version

%div.row
  %div.col-md-1
  %div.col-md-10
    .panel.panel-default
      .panel-heading
        %h4
          = "Set Location of OpenTripPlanner Server"
      .panel-body
        = simple_form_for @open_trip_planner, url: set_open_trip_planner_settings_path, html: {class: 'form-horizontal', multipart: true, method: 'patch' }, authenticity_token: true do |f|
          %div.col-md-10
            %label
              = "URL of the Open Trip Planner Server"
            = f.input :value, required:true, label: false, :as => :string, input_html: {style: "width:100%;"}
          %div.col-md-2.text-center
            = f.submit "OK", class: 'btn action-button', role: 'button'

%div.row
  %div.col-md-1
  %div.col-md-10
    .panel.panel-default
      .panel-heading
        %h4
          = "Set CallnRide Boundary"
      .panel-body
        %div.row
          = simple_form_for @boundary, url: set_callnride_boundary_settings_path, html: {class: 'form-horizontal', multipart: true, method: 'patch' }, authenticity_token: true do |f|
            %div.col-md-10
              %label
                = "Upload Zippled CallnRide Shapefile"
              = f.input "file", required:true, label: false, :as => :file
            %div.col-md-2.text-center
              = f.submit "OK", class: 'btn action-button', role: 'button'
        %div.row
          %div{id: 'mapid', style: "height:400px;"}

%div.row
  %div.col-md-1
  %div.col-md-10
    .panel.panel-default
      .panel-heading
        %h4
          = "Set Location of Landmarks File"
      .panel-body
        = simple_form_for @landmarks_file, url: set_landmarks_file_settings_path, html: {class: 'form-horizontal', multipart: true, method: 'patch' }, authenticity_token: true do |f|
          %div.col-md-10
            %label
              = "URL of the Landmarks File"
            = f.input :value, required:true, label: false, :as => :string, input_html: {style: "width:100%;"}
          %div.col-md-2.text-center
            = f.submit "OK", class: 'btn action-button', role: 'button'

%div.row
  %div.col-md-1
  %div.col-md-10
    .panel.panel-default
      .panel-heading
        %h4
          = "Set Location of Synonyms File"
      .panel-body
        = simple_form_for @synonyms_file, url: set_synonyms_file_settings_path, html: {class: 'form-horizontal', multipart: true, method: 'patch' }, authenticity_token: true do |f|
          %div.col-md-10
            %label
              = "URL of the Synonyms File"
            = f.input :value, required:true, label: false, :as => :string, input_html: {style: "width:100%;"}
          %div.col-md-2.text-center
            = f.submit "OK", class: 'btn action-button', role: 'button'

%div.row
  %div.col-md-1
  %div.col-md-10
    .panel.panel-default
      .panel-heading
        %h4
          = "Set Location of Blacklisted Google Places File"
      .panel-body
        = simple_form_for @blacklisted_places_file, url: set_blacklisted_places_file_settings_path, html: {class: 'form-horizontal', multipart: true, method: 'patch' }, authenticity_token: true do |f|
          %div.col-md-10
            %label
              = "URL of the Blacklisted Google Places File"
            = f.input :value, required:true, label: false, :as => :string, input_html: {style: "width:100%;"}
          %div.col-md-2.text-center
            = f.submit "OK", class: 'btn action-button', role: 'button'

%div.row
  %div.col-md-1
  %div.col-md-10
    .panel.panel-default
      .panel-heading
        %h4
          = "Who gets emails when synonyms, stops, landmarks, etc. are updated?"
      .panel-body
        = simple_form_for @support_emails, url: set_support_emails_settings_path, html: {class: 'form-horizontal', multipart: true, method: 'patch' }, authenticity_token: true do |f|
          %div.col-md-10
            %label
              = "Email Address"
            = f.input :value, required:true, label: false, :as => :text, input_html: {style: "width:100%;"}
          %div.col-md-2.text-center
            = f.submit "OK", class: 'btn action-button', role: 'button'

%div.row
  %div.col-md-1
  %div.col-md-10
    .panel.panel-default
      .panel-heading
        %h4
          = "Set the Host"
      .panel-body
        = simple_form_for @host, url: set_host_settings_path, html: {class: 'form-horizontal', multipart: true, method: 'patch' }, authenticity_token: true do |f|
          %div.col-md-10
            %label
              = "Host address used when including images in emails"
            = f.input :value, required:true, label: false, :as => :string, input_html: {style: "width:100%;"}
          %div.col-md-2.text-center
            = f.submit "OK", class: 'btn action-button', role: 'button'

%div.row
  %div.col-md-1
  %div.col-md-10
    .panel.panel-default
      .panel-heading
        %h4
          = "Set Global Boundary"
      .panel-body
        = simple_form_for @global_boundary, url: set_global_boundary_settings_path, html: {class: 'form-horizontal', multipart: true, method: 'patch' }, authenticity_token: true do |f|
          %div.col-md-10
            %label
              = "WKT of the Global Boundary"
            = f.input :value, required:true, label: false, :as => :text, input_html: {rows: 5, style: "width:100%;"}
          %div.col-md-2.text-center
            = f.submit "OK", class: 'btn action-button', role: 'button'

:javascript

  var mymap = L.map('mapid').setView([39.7392, -104.99], 10);

  L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: '',
      maxZoom: 18,
      id: '',
      accessToken: ''
  }).addTo(mymap);


  var latlngs = JSON.parse('#{GeographyService.new.callnride_boundary_array}');
  var polygon = L.multiPolygon(latlngs, {color: 'red'}).addTo(mymap);
  // zoom the map to the polygon
  mymap.fitBounds(polygon.getBounds());